# .streamlit/secrets.toml
GEMINI_API_KEY = "AIzaSyB0wBJVffOnGmpQH2UaqNEznPXfpLVwvTU"

# Archivo: .streamlit/config.toml

[theme]
# Color de fondo principal
backgroundColor="#F0F2F6"
# Color de fondo de los bloques (sidebar, widgets)
secondaryBackgroundColor="#FFFFFF" 
# Color de texto
textColor="#262730"
# Color principal (usado en botones, links y barras de progreso)
primaryColor="#0068C9" 
# Fuente por defecto (sans serif o serif)
font="sans serif"